utils::globalVariables(c("P.value", "V2","revDiff","finecluster","rarecluster"))
#' Calculate SCIntRuler
#'
#' @param fullcluster A list of clusters that generated by the function `GetCluster()`
#' @param seuratlist A list of Seurat objects, usually can be got by `SplitObject()`.
#' @param testres Result from function `PermTest()`
#' @param p P-value that will be used as the cut-off, default value is 0.1
#'
#' @return SCIntRuler
#' @export
#'
#' @examples
#' \dontrun{
#' # Create example data for fullcluster (mock data)
#' seuratlist <- SplitObject(seuratobj, split.by = "Study")
#' fullcluster <- GetCluster(seuratist)
#' testres <- PermTest(fullcluster,distmat,15)
#' CalcuSCIR(fullcluster, seuratlist, testres)
#' }
#'

CalcuSCIR <- function(fullcluster, seuratlist, testres, p = 0.1){

  SCout <- SummCluster(fullcluster)
  refindClust <- SCout$refindClust
  nbroad <- SCout$nbroad
  allrevDiff <- testres$allrevDiff
  allP <- testres$allP


  Sample <- c()
  for (i in 1:length(allP)){
    l <- length(allP[[i]])
    ll <- rep(names(seuratlist)[i],l)
    Sample <- c(Sample,ll)
  }

  res <- data.frame("P value"=unlist(allP), revDiff = na.omit(c(allrevDiff)), Sample)
  ratio <- dim(subset(res, P.value <= p & revDiff > 0))[1]/length(Sample)

  return(ratio)


}
