#' Permutation Test
#'
#' @param fullcluster A list of clusters that generated by the function GetCluster()
#' @param firstn Positive integer giving the number of nearest neighbors from
#'   each sampled cell to include. It must not exceed the `meaningn` value used
#'   to create `distmat`. The published method uses 15.
#' @param distmat A list of distance vectors generated by the function FindNNDist().
#'
#' @return A list containing the relative within-between distance matrix
#'   (`allrevDiff`) and permutation-test p-values (`allP`).
#' @export
#'
#' @examples
#' data(sim_result)
#' test_result <- PermTest(sim_result[[1]], sim_result[[3]], firstn = 15)
#' test_result$allrevDiff

PermTest <- function(fullcluster, distmat, firstn = 15) {

  stopifnot(exprs = {
    is.list(fullcluster)
    is.list(distmat)
  })
  firstn <- .validate_firstn(firstn)


  allP <- list()

  nclust <- rep(NA, length(fullcluster))

  for(i in seq_along(fullcluster)) {
    nclust[i] <- max(fullcluster[[i]]$finecluster)
  }

  allrevDiff <- matrix(NA, max(nclust), length(fullcluster))

  for (j in seq_along(fullcluster)) {

    revDiff <- rep(NA, nclust[j])
    onep_vec <- rep(NA, length(distmat[[j]][[1]]))

    for (q in seq_len(nclust[j])) {

      dist1 <- .extract_nearest_distances(
        distmat[[j]][[1]][[q]], firstn, "within-cluster"
      )
      dist2 <- .extract_nearest_distances(
        distmat[[j]][[2]][[q]], firstn, "between-cluster"
      )

      revDiff[q] <- (mean(dist2) - mean(dist1))/max(mean(dist2),mean(dist1))

      # disttest <- data.frame(rbind(cbind(dist1,rep("Internal Dist",length(dist1))),
      #                              cbind(dist2,rep("External Dist",length(dist2)))))%>%
      #   dplyr::mutate(dist = as.numeric(dist1),group = factor(V2)) %>% dplyr::select(3,4)

      # Using Native Pipe
      # disttest <- data.frame(rbind(cbind(dist1, rep("Internal Dist", length(dist1))),
      #                              cbind(dist2, rep("External Dist", length(dist2))))) |>
      #   (\(df) dplyr::mutate(df, dist = as.numeric(dist1), group = factor(V2)))() |>
      #   (\(df) dplyr::select(df, 3, 4))()

      # Without Pipes
      dist_combined <- data.frame(rbind(cbind(dist1, rep("Internal Dist", length(dist1))),
                                        cbind(dist2, rep("External Dist", length(dist2)))))
      disttest <- dplyr::mutate(dist_combined, dist = as.numeric(dist1), group = factor(V2))
      disttest <- dplyr::select(disttest, 3, 4)


      onep_vec[q] <- round(coin::pvalue(coin::independence_test(dist ~ group, data = disttest,
                                                    alternative = "greater")),3)


    }

    allrevDiff[1:nclust[j], j] <- revDiff
    allP[[j]] <- onep_vec

  }

  return(list(allrevDiff = allrevDiff,
              allP = allP))

}

.validate_firstn <- function(firstn) {
  valid <- is.numeric(firstn) && length(firstn) == 1L &&
    !is.na(firstn) && is.finite(firstn) && firstn >= 1 &&
    firstn == as.integer(firstn)
  if (!valid) {
    stop("`firstn` must be one positive integer.", call. = FALSE)
  }
  as.integer(firstn)
}

.extract_nearest_distances <- function(distances, firstn, label) {
  distance_matrix <- do.call(cbind, distances)
  if (is.null(dim(distance_matrix))) {
    distance_matrix <- matrix(distance_matrix, ncol = 1L)
  }
  if (nrow(distance_matrix) < firstn) {
    stop(
      sprintf(
        "`firstn` (%d) exceeds the %d stored %s nearest neighbors; rerun FindNNDist() or FindNNDistC() with `meaningn >= firstn`.",
        firstn, nrow(distance_matrix), label
      ),
      call. = FALSE
    )
  }
  as.vector(distance_matrix[seq_len(firstn), , drop = FALSE])
}
