#' Plot SCIntRuler
#'
#' @param fullcluster A list of clusters that generated by the function `GetCluster`.
#' @param seuratlist A list of Seurat objects, usually can be got by `SplitObject()`.
#' @param testres Result from function `PermTest()`
#' @param legendtitle Title of legend, default to be `NULL`
#' @param title Title of figure, default to be `NULL`
#'
#' @return  A ggplot2 object
#' @export
#'
#' @examples
#' \dontrun{
#' # Create example data for fullcluster (mock data)
#' seuratlist <- SplitObject(seuratobj, split.by = "Study")
#' fullcluster <- GetCluster(seurat_object_list)
#' testres <- PermTest(fullcluster,distmat,15)
#' PlotSCIR(fullcluster, seuratlist, testres)
#' }
PlotSCIR <- function(fullcluster,seuratlist,testres,legendtitle= NULL,title = NULL) {

  stopifnot(exprs = {
    is.list(fullcluster)
    is.list(seuratlist)
    is.list(testres)
  })


  SCout <- SummCluster(fullcluster)
  refindClust <- SCout$refindClust
  nbroad <- SCout$nbroad
  allrevDiff <- testres$allrevDiff
  allP <- testres$allP


  Sample <- c()
  for (i in 1:length(allP)){
    l <- length(allP[[i]])
    ll <- rep(names(seuratlist)[i],l)
    Sample <- c(Sample,ll)
  }

  res <- data.frame("P value"=unlist(allP), revDiff = na.omit(c(allrevDiff)), Sample)
  ratio <- dim(subset(res, P.value <0.1 & revDiff >0))[1]/length(Sample)

  plot <- res %>%
    ggplot2::ggplot() +
    ggplot2::geom_point(ggplot2::aes(revDiff,`P.value`,color = factor(Sample)), size = 3, alpha = 0.7) +
    ggplot2::theme_test()+
    ggplot2::scale_color_brewer(palette= "Dark2") +
    ggplot2::geom_hline(yintercept=0.1, linetype="dashed", color = "blue") +
    ggplot2::geom_vline(xintercept=0, linetype="dashed", color = "red")+
    ggplot2::ylab("P-value") + ggplot2::xlab("Within-between Cluster Relative Distance")+
    ggplot2::annotate("text", x = max(allrevDiff, na.rm = T), y = max(unlist(allP)/2, na.rm = T),
             label= paste("SCIntRuler =",round(ratio,2)),hjust=1, fontface="bold")+
    ggplot2::labs(color= legendtitle) +
    ggplot2::ggtitle(title)+
    ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size=2)))

  return(plot)



}
