# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossdist <- function(m1, m2) {
    .Call('_SCIntRuler_crossdist', PACKAGE = 'SCIntRuler', m1, m2)
}

