#' Get maximum number of broad clusters
#'
#' @param fullcluster A list of clusters that generated by the function `GetCluster()`
#'
#' @return A list
#' @export
#'
#' @examples
#' \dontrun{
#' # Assuming 'fullcluster' is a list of clusters
#' fullcluster <- GetCluster(seuratlist)
#' SCout <- SummCluster(fullcluster)
#' }
SummCluster <- function(fullcluster) {
  nbroad <- c()
  refindClust <- list()
  for(i in 1:length(fullcluster)) {
    nbroad <- c(nbroad, length(unique(fullcluster[[i]]$broadcluster)))

    onetmp <- fullcluster[[i]][which(!duplicated(fullcluster[[i]][,2])), ]
    refindClust[[i]] <- onetmp[order(onetmp[,2]), ]
  }

  return(list(nbroad = nbroad,
              refindClust = refindClust))
}
